"""#001 First attempt to create Address table

Revision ID: 2d4717528c96
Revises: 46c5847ef2ed
Create Date: 2025-08-17 16:15:50.898881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4717528c96'
down_revision: Union[str, Sequence[str], None] = '46c5847ef2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('neighbourhood', sa.String(length=60), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('place_number', sa.String(length=10), nullable=True),
    sa.Column('additional_info', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=8), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'phone_numbers', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_numbers', type_='unique')
    op.drop_table('addresses')
    # ### end Alembic commands ###
