"""Fix: employee email field

Revision ID: 7bcc5d2a32af
Revises: 8784a5bf3643
Create Date: 2025-08-21 22:04:44.843537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcc5d2a32af'
down_revision: Union[str, Sequence[str], None] = '8784a5bf3643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'employees',
        'email',
        existing_type= sa.String(length=8),
        type_=sa.String(length=100),
        existing_nullable=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'employees',
        'email',
        existing_type= sa.String(length=8),
        type_=sa.String(length=100),
        existing_nullable=False
    )

