"""Employee table implementation

Revision ID: 8784a5bf3643
Revises: 2d4717528c96
Create Date: 2025-08-21 21:36:48.142595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))
from app.security import HashedPassword

# revision identifiers, used by Alembic.
revision: str = '8784a5bf3643'
down_revision: Union[str, Sequence[str], None] = '2d4717528c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=8), nullable=False),
    sa.Column('password', HashedPassword(), nullable=False),
    sa.Column('dateOfBirth', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'editor', 'admin', name='rolesenum'), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=True)
    op.create_unique_constraint(None, 'addresses', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='unique')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
