[default]

[default.db]

uri = ""
connect_args = {check_same_thread=false}
echo = true

[default.security]

# SECRET_KEY = ""
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 10
REFRESH_TOKEN_EXPIRE_MINUTES = 200